# Information 
name = "Polar-Bear"
license = "MIT"
licenselink = "https://codeberg.org/east/Polar-Bear/src/branch/master/LICENSE"
description = "Hugo theme based on Hugo Bear Blog & Bear Blog"

# Theme homepage.
homepage = "https://codeberg.org/east/Polar-Bear/"

# Theme demo site.
demosite = ""

# Aspects
tags = ["blog", "responsive", "light", "minimalist"]
features = ["favicon", "seo", "rss",]

# Authors 
[author]
  name = "east"
  homepage = "https://www.eastz.org"

# If porting an existing theme
[original]
  author = "Jan Raasch"
  homepage = "https://www.janraasch.com"
  repo = "https://github.com/janraasch/hugo-bearblog"

# Hugo Version
min_version = "0.73.0"